/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

import ec.edu.ups.proyectobiblioteca.enums.CategoriasLibro;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class ActualizarLibroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarLibroView
     */
    public ActualizarLibroView() {
        initComponents();
        cargarAnios();
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public void setBtnActualizar(JButton btnActualizar) {
        this.btnActualizar = btnActualizar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JComboBox<String> getCboAutorActualizar() {
        return cboAutorActualizar;
    }

    public void setCboAutorActualizar(JComboBox<String> cboAutorActualizar) {
        this.cboAutorActualizar = cboAutorActualizar;
    }

    public JComboBox<String> getComboBoxAnio() {
        return ComboBoxAnio;
    }

    public void setComboBoxAnio(JComboBox<String> ComboBoxAnio) {
        this.ComboBoxAnio = ComboBoxAnio;
    }

    public JComboBox<String> getComboBoxDia() {
        return ComboBoxDia;
    }

    public void setComboBoxDia(JComboBox<String> ComboBoxDia) {
        this.ComboBoxDia = ComboBoxDia;
    }

    public JComboBox<String> getComboBoxMes() {
        return ComboBoxMes;
    }

    public void setComboBoxMes(JComboBox<String> ComboBoxMes) {
        this.ComboBoxMes = ComboBoxMes;
    }

    public JTextField getTxtEditorialActualizar() {
        return txtEditorialActualizar;
    }

    public void setTxtEditorialActualizar(JTextField txtEditorialActualizar) {
        this.txtEditorialActualizar = txtEditorialActualizar;
    }

    public JTextField getTxtISBNActualizar() {
        return txtISBNActualizar;
    }

    public void setTxtISBNActualizar(JTextField txtISBNActualizar) {
        this.txtISBNActualizar = txtISBNActualizar;
    }

    public JTextField getTxtTituloActualizar() {
        return txtTituloActualizar;
    }

    public void setTxtTituloActualizar(JTextField txtTituloActualizar) {
        this.txtTituloActualizar = txtTituloActualizar;
    }

    private void cargarAnios() {
        int actual = java.time.Year.now().getValue();

        for (int i = actual - 100; i <= actual; i++) {
            ComboBoxAnio.addItem(String.valueOf(i));
        }

    }

    public JComboBox<CategoriasLibro> getCboCategoriaActualizar() {
        return cboCategoriaActualizar;
    }

    public void setCboCategoriaActualizar(JComboBox<CategoriasLibro> cboCategoriaActualizar) {
        this.cboCategoriaActualizar = cboCategoriaActualizar;
    }

    public void cambiarIdioma(Locale locale) {

        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.proyectobiblioteca.i18n.mensajes", locale);

        setTitle(bundle.getString("tituloVentanaActualizarLibro"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("tituloPanelActualizarLibro")));

        lblISBNActualizar.setText(bundle.getString("lblISBNLibro"));
        lblTituloActualizar.setText(bundle.getString("lblTituloLibro"));
        lblFechaActualizar.setText(bundle.getString("lblFechaPubLibro"));
        lblAutorActualizar.setText(bundle.getString("lblAutorLibro"));
        lblCategoriaActualizar.setText(bundle.getString("lblCategoriaLibro"));
        lblEditorialActualizar.setText(bundle.getString("lblEditorialLibro"));

        btnBuscar.setText(bundle.getString("btnBuscar"));
        btnActualizar.setText(bundle.getString("actualizarMenuItem"));
        btnCancelar.setText(bundle.getString("btnCancelar"));
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblISBNActualizar = new javax.swing.JLabel();
        txtISBNActualizar = new javax.swing.JTextField();
        lblTituloActualizar = new javax.swing.JLabel();
        txtTituloActualizar = new javax.swing.JTextField();
        lblFechaActualizar = new javax.swing.JLabel();
        lblAutorActualizar = new javax.swing.JLabel();
        lblCategoriaActualizar = new javax.swing.JLabel();
        cboAutorActualizar = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        lblEditorialActualizar = new javax.swing.JLabel();
        txtEditorialActualizar = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        ComboBoxDia = new javax.swing.JComboBox<>();
        ComboBoxMes = new javax.swing.JComboBox<>();
        ComboBoxAnio = new javax.swing.JComboBox<>();
        cboCategoriaActualizar = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Libro");

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar libro con ISBN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 12))); // NOI18N

        lblISBNActualizar.setText("Ingrese el ISBN del libro:");

        lblTituloActualizar.setText("Título:");

        lblFechaActualizar.setText("Fecha de publicacion:");

        lblAutorActualizar.setText("Autor:");

        lblCategoriaActualizar.setText("Categoría:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/proyectobiblioteca/images/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        lblEditorialActualizar.setText("Editorial:");

        txtEditorialActualizar.addActionListener(this::txtEditorialActualizarActionPerformed);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/proyectobiblioteca/images/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        ComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblFechaActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTituloActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblAutorActualizar)
                            .addComponent(lblCategoriaActualizar)
                            .addComponent(lblEditorialActualizar))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(ComboBoxAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboCategoriaActualizar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTituloActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboAutorActualizar, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE)
                                .addComponent(txtEditorialActualizar, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActualizar)
                            .addComponent(lblISBNActualizar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtISBNActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnBuscar)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBNActualizar)
                    .addComponent(txtISBNActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloActualizar)
                    .addComponent(txtTituloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaActualizar)
                    .addComponent(ComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorActualizar)
                    .addComponent(cboAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaActualizar)
                    .addComponent(cboCategoriaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditorialActualizar)
                    .addComponent(txtEditorialActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditorialActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxAnio;
    private javax.swing.JComboBox<String> ComboBoxDia;
    private javax.swing.JComboBox<String> ComboBoxMes;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboAutorActualizar;
    private javax.swing.JComboBox<CategoriasLibro> cboCategoriaActualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutorActualizar;
    private javax.swing.JLabel lblCategoriaActualizar;
    private javax.swing.JLabel lblEditorialActualizar;
    private javax.swing.JLabel lblFechaActualizar;
    private javax.swing.JLabel lblISBNActualizar;
    private javax.swing.JLabel lblTituloActualizar;
    private javax.swing.JTextField txtEditorialActualizar;
    private javax.swing.JTextField txtISBNActualizar;
    private javax.swing.JTextField txtTituloActualizar;
    // End of variables declaration//GEN-END:variables
}
