/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class ActualizarPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarPrestamoView
     */
    public ActualizarPrestamoView() {
        initComponents();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JTextField getTxtCodigoActualizar() {
        return txtCodigoActualizar;
    }

    public void setTxtCodigoActualizar(JTextField txtCodigoActualizar) {
        this.txtCodigoActualizar = txtCodigoActualizar;
    }

    public JTextField getTxtFechaActualizar() {
        return txtFechaActualizar;
    }

    public void setTxtFechaActualizar(JTextField txtFechaActualizar) {
        this.txtFechaActualizar = txtFechaActualizar;
    }

    public JTextField getTxtFechaDevActualizar() {
        return txtFechaDevActualizar;
    }

    public void setTxtFechaDevActualizar(JTextField txtFechaDevActualizar) {
        this.txtFechaDevActualizar = txtFechaDevActualizar;
    }

    public JTextField getTxtLibroActualizar() {
        return txtLibroActualizar;
    }

    public void setTxtLibroActualizar(JTextField txtLibroActualizar) {
        this.txtLibroActualizar = txtLibroActualizar;
    }

    public JTextField getTxtUsuarioActualizar() {
        return txtUsuarioActualizar;
    }

    public void setTxtUsuarioActualizar(JTextField txtUsuarioActualizar) {
        this.txtUsuarioActualizar = txtUsuarioActualizar;
    }

    public JTextField getTxtAutorActualizar() {
        return txtAutorActualizar;
    }

    public void setTxtAutorActualizar(JTextField txtAutorActualizar) {
        this.txtAutorActualizar = txtAutorActualizar;
    }

    public JTextField getTxtISBNActualizar() {
        return txtISBNActualizar;
    }

    public void setTxtISBNActualizar(JTextField txtISBNActualizar) {
        this.txtISBNActualizar = txtISBNActualizar;
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigoActualizar = new javax.swing.JLabel();
        txtCodigoActualizar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblUsuarioActualizar = new javax.swing.JLabel();
        txtUsuarioActualizar = new javax.swing.JTextField();
        lblLibroActualizar = new javax.swing.JLabel();
        txtLibroActualizar = new javax.swing.JTextField();
        lblFechaActualizar = new javax.swing.JLabel();
        txtFechaActualizar = new javax.swing.JTextField();
        lblFechaDevActualizar = new javax.swing.JLabel();
        txtFechaDevActualizar = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblLectura1 = new javax.swing.JLabel();
        lblLectura2 = new javax.swing.JLabel();
        lblLectura3 = new javax.swing.JLabel();
        lblAutorActualizar = new javax.swing.JLabel();
        txtAutorActualizar = new javax.swing.JTextField();
        lblLectura4 = new javax.swing.JLabel();
        lblISBNActualizar = new javax.swing.JLabel();
        txtISBNActualizar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Prestamo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar datos del prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 12))); // NOI18N

        lblCodigoActualizar.setText("Ingrese el codigo del prestamo:");

        btnBuscar.setText("Buscar");

        lblUsuarioActualizar.setText("Usuario:");

        txtUsuarioActualizar.setEditable(false);

        lblLibroActualizar.setText("Libro:");

        txtLibroActualizar.setEditable(false);

        lblFechaActualizar.setText("Fecha del prestamo:");

        txtFechaActualizar.setEditable(false);

        lblFechaDevActualizar.setText("Fecha de devolución:");

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        lblLectura1.setText("(solo lectura)");

        lblLectura2.setText("(solo lectura)");

        lblLectura3.setText("(solo lectura)");

        lblAutorActualizar.setText("Autor:");

        txtAutorActualizar.setEditable(false);
        txtAutorActualizar.addActionListener(this::txtAutorActualizarActionPerformed);

        lblLectura4.setText("(solo lectura)");

        lblISBNActualizar.setText("ISBN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnAceptar)
                .addGap(80, 80, 80)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodigoActualizar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuarioActualizar)
                                    .addComponent(lblLibroActualizar))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuarioActualizar)
                                    .addComponent(txtLibroActualizar)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblISBNActualizar)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAutorActualizar)
                                    .addComponent(txtISBNActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodigoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLectura4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblLectura1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblLectura2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaDevActualizar)
                            .addComponent(lblFechaActualizar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaDevActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFechaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLectura3))))
                    .addComponent(lblAutorActualizar))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoActualizar)
                    .addComponent(txtCodigoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioActualizar)
                    .addComponent(txtUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLectura1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibroActualizar)
                    .addComponent(txtLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLectura2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBNActualizar)
                    .addComponent(txtISBNActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLectura4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaActualizar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLectura3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDevActualizar)
                    .addComponent(txtFechaDevActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAutorActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutorActualizar;
    private javax.swing.JLabel lblCodigoActualizar;
    private javax.swing.JLabel lblFechaActualizar;
    private javax.swing.JLabel lblFechaDevActualizar;
    private javax.swing.JLabel lblISBNActualizar;
    private javax.swing.JLabel lblLectura1;
    private javax.swing.JLabel lblLectura2;
    private javax.swing.JLabel lblLectura3;
    private javax.swing.JLabel lblLectura4;
    private javax.swing.JLabel lblLibroActualizar;
    private javax.swing.JLabel lblUsuarioActualizar;
    private javax.swing.JTextField txtAutorActualizar;
    private javax.swing.JTextField txtCodigoActualizar;
    private javax.swing.JTextField txtFechaActualizar;
    private javax.swing.JTextField txtFechaDevActualizar;
    private javax.swing.JTextField txtISBNActualizar;
    private javax.swing.JTextField txtLibroActualizar;
    private javax.swing.JTextField txtUsuarioActualizar;
    // End of variables declaration//GEN-END:variables
}
