/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mateo
 */
public class AgregarAutorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearAutorView
     */
    public AgregarAutorView() {
        initComponents();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JTextField getTxtCodigoAgregarAutorView() {
        return txtCodigoAgregarAutorView;
    }

    public void setTxtCodigoAgregarAutorView(JTextField txtCodigoAgregarAutorView) {
        this.txtCodigoAgregarAutorView = txtCodigoAgregarAutorView;
    }

    public JTextField getTxtNacionalidadAgregarAutorView() {
        return txtNacionalidadAgregarAutorView;
    }

    public void setTxtNacionalidadAgregarAutorView(JTextField txtNacionalidadAgregarAutorView) {
        this.txtNacionalidadAgregarAutorView = txtNacionalidadAgregarAutorView;
    }

    public JTextField getTxtNombreAgregarAutorView() {
        return txtNombreAgregarAutorView;
    }

    public void setTxtNombreAgregarAutorView(JTextField txtNombreAgregarAutorView) {
        this.txtNombreAgregarAutorView = txtNombreAgregarAutorView;
    }

    public void cambiarIdioma(Locale locale) {

        ResourceBundle bundle = ResourceBundle.getBundle(
                "ec.edu.ups.proyectobiblioteca.i18n.mensajes", locale);

        setTitle(bundle.getString("tituloVentanaAgregarAutor"));

        jLabel1.setText(bundle.getString("lblCodigoAutor"));
        jLabel2.setText(bundle.getString("lblNombreAutor"));
        jLabel3.setText(bundle.getString("lblNacionalidadAutor"));

        btnAceptar.setText(bundle.getString("botonAceptar"));
        btnCancelar.setText(bundle.getString("botonCancelar"));
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoAgregarAutorView = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreAgregarAutorView = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNacionalidadAgregarAutorView = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar Autor");

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        txtNombreAgregarAutorView.addActionListener(this::txtNombreAgregarAutorViewActionPerformed);

        jLabel3.setText("Nacionalidad:");

        txtNacionalidadAgregarAutorView.addActionListener(this::txtNacionalidadAgregarAutorViewActionPerformed);

        btnAceptar.setText("Agregar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreAgregarAutorView, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtCodigoAgregarAutorView)
                            .addComponent(txtNacionalidadAgregarAutorView))
                        .addContainerGap(112, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoAgregarAutorView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreAgregarAutorView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNacionalidadAgregarAutorView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNombreAgregarAutorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAgregarAutorViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAgregarAutorViewActionPerformed

    private void txtNacionalidadAgregarAutorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadAgregarAutorViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadAgregarAutorViewActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCodigoAgregarAutorView;
    private javax.swing.JTextField txtNacionalidadAgregarAutorView;
    private javax.swing.JTextField txtNombreAgregarAutorView;
    // End of variables declaration//GEN-END:variables
}
