/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

/**
 *
 * @author Asus
 */
public class AgregarLibroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarLibroVIew
     */
    public AgregarLibroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblISBNAgregar = new javax.swing.JLabel();
        txtISBNAgregar = new javax.swing.JTextField();
        lblTituloAgregar = new javax.swing.JLabel();
        lblAutorAgregar = new javax.swing.JLabel();
        txtTituloAgregar = new javax.swing.JTextField();
        cboAutorAgregar = new javax.swing.JComboBox<>();
        lblCategoriaAgregar = new javax.swing.JLabel();
        cboCategoriaAgregar = new javax.swing.JComboBox<>();
        lblFechaAgregar = new javax.swing.JLabel();
        temporal = new javax.swing.JTextField();
        lblDateFormatAgregar = new javax.swing.JLabel();
        lblEditorialAgregar = new javax.swing.JLabel();
        txtEditorialAgregar = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Libro");

        jPanel1.setBackground(java.awt.Color.pink);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar un nuevo Libro\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 12))); // NOI18N

        lblISBNAgregar.setText("Ingrese el ISBN:");

        lblTituloAgregar.setText("Titulo:");

        lblAutorAgregar.setText("Autor:");

        cboAutorAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCategoriaAgregar.setText("Categoria:");

        cboCategoriaAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFechaAgregar.setText("Fecha de publicacion:");

        temporal.addActionListener(this::temporalActionPerformed);

        lblDateFormatAgregar.setText("dd/mm/yyyy");

        lblEditorialAgregar.setText("Editorial:");

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblISBNAgregar)
                        .addComponent(lblTituloAgregar)
                        .addComponent(lblAutorAgregar)
                        .addComponent(lblCategoriaAgregar)
                        .addComponent(lblFechaAgregar)
                        .addComponent(lblEditorialAgregar)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtISBNAgregar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTituloAgregar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboAutorAgregar, javax.swing.GroupLayout.Alignment.LEADING, 0, 113, Short.MAX_VALUE)
                        .addComponent(cboCategoriaAgregar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(temporal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEditorialAgregar, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnCancelar))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDateFormatAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBNAgregar)
                    .addComponent(txtISBNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloAgregar)
                    .addComponent(txtTituloAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutorAgregar)
                    .addComponent(cboAutorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategoriaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoriaAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDateFormatAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaAgregar)
                    .addComponent(temporal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorialAgregar)
                    .addComponent(txtEditorialAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temporalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temporalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboAutorAgregar;
    private javax.swing.JComboBox<String> cboCategoriaAgregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutorAgregar;
    private javax.swing.JLabel lblCategoriaAgregar;
    private javax.swing.JLabel lblDateFormatAgregar;
    private javax.swing.JLabel lblEditorialAgregar;
    private javax.swing.JLabel lblFechaAgregar;
    private javax.swing.JLabel lblISBNAgregar;
    private javax.swing.JLabel lblTituloAgregar;
    private javax.swing.JTextField temporal;
    private javax.swing.JTextField txtEditorialAgregar;
    private javax.swing.JTextField txtISBNAgregar;
    private javax.swing.JTextField txtTituloAgregar;
    // End of variables declaration//GEN-END:variables
}
