/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class BuscarLibroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarLibroView
     */
    public BuscarLibroView() {
        initComponents();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JTextField getTxtAutorBuscar() {
        return txtAutorBuscar;
    }

    public void setTxtAutorBuscar(JTextField txtAutorBuscar) {
        this.txtAutorBuscar = txtAutorBuscar;
    }

    public JTextField getTxtCategoriaBuscar() {
        return txtCategoriaBuscar;
    }

    public void setTxtCategoriaBuscar(JTextField txtCategoriaBuscar) {
        this.txtCategoriaBuscar = txtCategoriaBuscar;
    }

    public JTextField getTxtEditorialBuscar() {
        return txtEditorialBuscar;
    }

    public void setTxtEditorialBuscar(JTextField txtEditorialBuscar) {
        this.txtEditorialBuscar = txtEditorialBuscar;
    }

    public JTextField getTxtEstadoBuscar() {
        return txtEstadoBuscar;
    }

    public void setTxtEstadoBuscar(JTextField txtEstadoBuscar) {
        this.txtEstadoBuscar = txtEstadoBuscar;
    }

    public JTextField getTxtFechaBuscar() {
        return txtFechaBuscar;
    }

    public void setTxtFechaBuscar(JTextField txtFechaBuscar) {
        this.txtFechaBuscar = txtFechaBuscar;
    }

    public JTextField getTxtISBNBuscar() {
        return txtISBNBuscar;
    }

    public void setTxtISBNBuscar(JTextField txtISBNBuscar) {
        this.txtISBNBuscar = txtISBNBuscar;
    }

    public JTextField getTxtTituloBuscar() {
        return txtTituloBuscar;
    }

    public void setTxtTituloBuscar(JTextField txtTituloBuscar) {
        this.txtTituloBuscar = txtTituloBuscar;
    }

    public void cambiarIdioma(Locale locale) {

        ResourceBundle bundle = ResourceBundle.getBundle(
                "ec.edu.ups.proyectobiblioteca.i18n.mensajes", locale);

        setTitle(bundle.getString("tituloVentanaBuscarLibro"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("tituloPanelBuscarLibro")));

        lblISBNBuscar.setText(bundle.getString("lblISBNLibro"));
        lblTituloBuscar.setText(bundle.getString("lblTituloLibro"));
        lblAutorBuscar.setText(bundle.getString("lblAutorLibro"));
        lblFechaBuscar.setText(bundle.getString("lblFechaPubLibro"));
        lblCategoriaBuscar.setText(bundle.getString("lblCategoriaLibro"));
        lblEditorialBuscar.setText(bundle.getString("lblEditorialLibro"));
        lblEstadoBuscar.setText(bundle.getString("lblEstadoLibro"));

        btnBuscar.setText(bundle.getString("btnBuscar"));
        btnAceptar.setText(bundle.getString("btnAceptar"));
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblISBNBuscar = new javax.swing.JLabel();
        txtISBNBuscar = new javax.swing.JTextField();
        lblTituloBuscar = new javax.swing.JLabel();
        lblAutorBuscar = new javax.swing.JLabel();
        lblFechaBuscar = new javax.swing.JLabel();
        lblCategoriaBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblEditorialBuscar = new javax.swing.JLabel();
        lblEstadoBuscar = new javax.swing.JLabel();
        txtTituloBuscar = new javax.swing.JTextField();
        txtAutorBuscar = new javax.swing.JTextField();
        txtFechaBuscar = new javax.swing.JTextField();
        txtCategoriaBuscar = new javax.swing.JTextField();
        txtEditorialBuscar = new javax.swing.JTextField();
        txtEstadoBuscar = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Libro");

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Libro con su ISBN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 12))); // NOI18N

        lblISBNBuscar.setText("Ingrese el ISBN del libro:");

        lblTituloBuscar.setText("Titulo:");

        lblAutorBuscar.setText("Autor:");

        lblFechaBuscar.setText("Fecha de publicación:");

        lblCategoriaBuscar.setText("Categoría:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        lblEditorialBuscar.setText("Editorial:");

        lblEstadoBuscar.setText("Estado:");

        txtTituloBuscar.setEnabled(false);

        txtAutorBuscar.setEnabled(false);
        txtAutorBuscar.addActionListener(this::txtAutorBuscarActionPerformed);

        txtFechaBuscar.setEnabled(false);

        txtCategoriaBuscar.setEnabled(false);

        txtEditorialBuscar.setEnabled(false);

        txtEstadoBuscar.setEnabled(false);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/proyectobiblioteca/images/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblISBNBuscar)
                        .addComponent(lblEstadoBuscar)
                        .addComponent(lblEditorialBuscar)
                        .addComponent(lblCategoriaBuscar)
                        .addComponent(lblFechaBuscar)
                        .addComponent(lblAutorBuscar)
                        .addComponent(lblTituloBuscar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtISBNBuscar)
                                .addComponent(txtTituloBuscar)
                                .addComponent(txtAutorBuscar)
                                .addComponent(txtFechaBuscar)
                                .addComponent(txtCategoriaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txtEditorialBuscar))
                            .addComponent(txtEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnBuscar)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBNBuscar)
                    .addComponent(txtISBNBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloBuscar)
                    .addComponent(txtTituloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorBuscar)
                    .addComponent(txtAutorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaBuscar)
                    .addComponent(txtFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategoriaBuscar)
                    .addComponent(txtCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditorialBuscar)
                    .addComponent(txtEditorialBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoBuscar)
                    .addComponent(txtEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnBuscar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtAutorBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutorBuscar;
    private javax.swing.JLabel lblCategoriaBuscar;
    private javax.swing.JLabel lblEditorialBuscar;
    private javax.swing.JLabel lblEstadoBuscar;
    private javax.swing.JLabel lblFechaBuscar;
    private javax.swing.JLabel lblISBNBuscar;
    private javax.swing.JLabel lblTituloBuscar;
    private javax.swing.JTextField txtAutorBuscar;
    private javax.swing.JTextField txtCategoriaBuscar;
    private javax.swing.JTextField txtEditorialBuscar;
    private javax.swing.JTextField txtEstadoBuscar;
    private javax.swing.JTextField txtFechaBuscar;
    private javax.swing.JTextField txtISBNBuscar;
    private javax.swing.JTextField txtTituloBuscar;
    // End of variables declaration//GEN-END:variables
}
