/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class BuscarPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPrestamoView
     */
    public BuscarPrestamoView() {
        initComponents();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JTextField getTxtAutorBuscar() {
        return txtAutorBuscar;
    }

    public void setTxtAutorBuscar(JTextField txtAutorBuscar) {
        this.txtAutorBuscar = txtAutorBuscar;
    }

    public JTextField getTxtCedulaBuscar() {
        return txtCedulaBuscar;
    }

    public void setTxtCedulaBuscar(JTextField txtCedulaBuscar) {
        this.txtCedulaBuscar = txtCedulaBuscar;
    }

    public JTextField getTxtCodigoBuscar() {
        return txtCodigoBuscar;
    }

    public void setTxtCodigoBuscar(JTextField txtCodigoBuscar) {
        this.txtCodigoBuscar = txtCodigoBuscar;
    }

    public JTextField getTxtFechaBuscar() {
        return txtFechaBuscar;
    }

    public void setTxtFechaBuscar(JTextField txtFechaBuscar) {
        this.txtFechaBuscar = txtFechaBuscar;
    }

    public JTextField getTxtFechaDevBuscar() {
        return txtFechaDevBuscar;
    }

    public void setTxtFechaDevBuscar(JTextField txtFechaDevBuscar) {
        this.txtFechaDevBuscar = txtFechaDevBuscar;
    }

    public JTextField getTxtISBNBuscar() {
        return txtISBNBuscar;
    }

    public void setTxtISBNBuscar(JTextField txtISBNBuscar) {
        this.txtISBNBuscar = txtISBNBuscar;
    }

    public JTextField getTxtLibroBuscar() {
        return txtLibroBuscar;
    }

    public void setTxtLibroBuscar(JTextField txtLibroBuscar) {
        this.txtLibroBuscar = txtLibroBuscar;
    }

    public JTextField getTxtUsuarioBuscar() {
        return txtUsuarioBuscar;
    }

    public void setTxtUsuarioBuscar(JTextField txtUsuarioBuscar) {
        this.txtUsuarioBuscar = txtUsuarioBuscar;
    }

    public JTextField getTxtEstadoBuscar() {
        return txtEstadoBuscar;
    }

    public void setTxtEstadoBuscar(JTextField txtEstadoBuscar) {
        this.txtEstadoBuscar = txtEstadoBuscar;
    }

    public void cambiarIdioma(Locale locale) {

        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.proyectobiblioteca.i18n.mensajes", locale);

        setTitle(bundle.getString("tituloVentanaBuscarPrestamo"));

        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("tituloPanelBuscarPrestamo")));

        lblCodigoBuscar.setText(bundle.getString("lblCodigoPrestamo"));
        lblUsuarioBuscar.setText(bundle.getString("lblUsuarioPrestamo"));
        lblCedulaBuscar.setText(bundle.getString("lblCedulaPrestamo"));
        lblLibroBuscar.setText(bundle.getString("lblLibroPrestamo"));
        lblAutorBuscar.setText(bundle.getString("lblAutorPrestamo"));
        lblISBNBuscar.setText(bundle.getString("lblISBNPrestamo"));
        lblFechaBuscar.setText(bundle.getString("lblFechaPrestamo"));
        lblFechaDevBuscar.setText(bundle.getString("lblFechaDevPrestamo"));
        lblEstadoBuscar.setText(bundle.getString("lblEstadoPrestamo"));

        btnBuscar.setText(bundle.getString("btnBuscar"));
        btnAceptar.setText(bundle.getString("btnAceptar"));
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        lblCodigoBuscar = new javax.swing.JLabel();
        txtCodigoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblUsuarioBuscar = new javax.swing.JLabel();
        lblLibroBuscar = new javax.swing.JLabel();
        lblAutorBuscar = new javax.swing.JLabel();
        lblISBNBuscar = new javax.swing.JLabel();
        lblFechaBuscar = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtUsuarioBuscar = new javax.swing.JTextField();
        txtLibroBuscar = new javax.swing.JTextField();
        txtAutorBuscar = new javax.swing.JTextField();
        txtISBNBuscar = new javax.swing.JTextField();
        txtFechaBuscar = new javax.swing.JTextField();
        lblFechaDevBuscar = new javax.swing.JLabel();
        txtFechaDevBuscar = new javax.swing.JTextField();
        lblEstadoBuscar = new javax.swing.JLabel();
        lblCedulaBuscar = new javax.swing.JLabel();
        txtCedulaBuscar = new javax.swing.JTextField();
        txtEstadoBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Prestamo");

        panelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Fax", 0, 12))); // NOI18N
        panelBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        lblCodigoBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblCodigoBuscar.setText("Ingrese el código del préstamo:");

        btnBuscar.setBackground(java.awt.Color.pink);
        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/proyectobiblioteca/images/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        lblUsuarioBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblUsuarioBuscar.setText("Usuario:");

        lblLibroBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblLibroBuscar.setText("Libro:");

        lblAutorBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblAutorBuscar.setText("Autor");

        lblISBNBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblISBNBuscar.setText("ISBN:");

        lblFechaBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblFechaBuscar.setText("Fecha de préstamo:");

        btnAceptar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/proyectobiblioteca/images/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        txtUsuarioBuscar.setEditable(false);
        txtUsuarioBuscar.setEnabled(false);
        txtUsuarioBuscar.addActionListener(this::txtUsuarioBuscarActionPerformed);

        txtLibroBuscar.setEditable(false);
        txtLibroBuscar.setEnabled(false);

        txtAutorBuscar.setEditable(false);
        txtAutorBuscar.setEnabled(false);

        txtISBNBuscar.setEditable(false);
        txtISBNBuscar.setEnabled(false);

        txtFechaBuscar.setEditable(false);
        txtFechaBuscar.setEnabled(false);

        lblFechaDevBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblFechaDevBuscar.setText("Fecha de devolución:");

        txtFechaDevBuscar.setEditable(false);
        txtFechaDevBuscar.setEnabled(false);

        lblEstadoBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblEstadoBuscar.setText("Estado:");

        lblCedulaBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblCedulaBuscar.setText("Cédula:");

        txtCedulaBuscar.setEnabled(false);

        txtEstadoBuscar.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Préstamo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblISBNBuscar)
                            .addComponent(lblAutorBuscar))
                        .addGap(68, 68, 68)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISBNBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstadoBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaDevBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaDevBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLibroBuscar))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCedulaBuscar))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsuarioBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                        .addComponent(lblCodigoBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnAceptar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoBuscar)
                    .addComponent(btnBuscar))
                .addGap(24, 24, 24)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioBuscar)
                    .addComponent(txtUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedulaBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibroBuscar)
                    .addComponent(txtLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutorBuscar)
                    .addComponent(txtAutorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBNBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblISBNBuscar))
                .addGap(26, 26, 26)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaBuscar)
                    .addComponent(txtFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDevBuscar)
                    .addComponent(txtFechaDevBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoBuscar)
                    .addComponent(txtEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnAceptar)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAutorBuscar;
    private javax.swing.JLabel lblCedulaBuscar;
    private javax.swing.JLabel lblCodigoBuscar;
    private javax.swing.JLabel lblEstadoBuscar;
    private javax.swing.JLabel lblFechaBuscar;
    private javax.swing.JLabel lblFechaDevBuscar;
    private javax.swing.JLabel lblISBNBuscar;
    private javax.swing.JLabel lblLibroBuscar;
    private javax.swing.JLabel lblUsuarioBuscar;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JTextField txtAutorBuscar;
    private javax.swing.JTextField txtCedulaBuscar;
    private javax.swing.JTextField txtCodigoBuscar;
    private javax.swing.JTextField txtEstadoBuscar;
    private javax.swing.JTextField txtFechaBuscar;
    private javax.swing.JTextField txtFechaDevBuscar;
    private javax.swing.JTextField txtISBNBuscar;
    private javax.swing.JTextField txtLibroBuscar;
    private javax.swing.JTextField txtUsuarioBuscar;
    // End of variables declaration//GEN-END:variables
}
