/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class CrearPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearPrestamoView
     */
    public CrearPrestamoView() {
        initComponents();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JTextField getTxtCedulaCrear() {
        return txtCedulaCrear;
    }

    public void setTxtCedulaCrear(JTextField txtCedulaCrear) {
        this.txtCedulaCrear = txtCedulaCrear;
    }

    public JTextField getTxtCodigoCrear() {
        return txtCodigoCrear;
    }

    public void setTxtCodigoCrear(JTextField txtCodigoCrear) {
        this.txtCodigoCrear = txtCodigoCrear;
    }

    public JTextField getTxtDisponibleCrear() {
        return txtDisponibleCrear;
    }

    public void setTxtDisponibleCrear(JTextField txtDisponibleCrear) {
        this.txtDisponibleCrear = txtDisponibleCrear;
    }

    public JTextField getTxtFechaCrear() {
        return txtFechaCrear;
    }

    public void setTxtFechaCrear(JTextField txtFechaCrear) {
        this.txtFechaCrear = txtFechaCrear;
    }

    public JTextField getTxtFechaDevCrear() {
        return txtFechaDevCrear;
    }

    public void setTxtFechaDevCrear(JTextField txtFechaDevCrear) {
        this.txtFechaDevCrear = txtFechaDevCrear;
    }

    public JTextField getTxtISBNCrear() {
        return txtISBNCrear;
    }

    public void setTxtISBNCrear(JTextField txtISBNCrear) {
        this.txtISBNCrear = txtISBNCrear;
    }

    public JButton getBtnBuscarLibro() {
        return btnBuscarLibro;
    }

    public void setBtnBuscarLibro(JButton btnBuscarLibro) {
        this.btnBuscarLibro = btnBuscarLibro;
    }

    public JButton getBtnBuscarUsuario() {
        return btnBuscarUsuario;
    }

    public void setBtnBuscarUsuario(JButton btnBuscarUsuario) {
        this.btnBuscarUsuario = btnBuscarUsuario;
    }

    public JTextField getTxtAutorCrear() {
        return txtAutorCrear;
    }

    public void setTxtAutorCrear(JTextField txtAutorCrear) {
        this.txtAutorCrear = txtAutorCrear;
    }

    public JTextField getTxtLibroCrear() {
        return txtLibroCrear;
    }

    public void setTxtLibroCrear(JTextField txtLibroCrear) {
        this.txtLibroCrear = txtLibroCrear;
    }

    public JTextField getTxtUsuarioCrear() {
        return txtUsuarioCrear;
    }

    public void setTxtUsuarioCrear(JTextField txtUsuarioCrear) {
        this.txtUsuarioCrear = txtUsuarioCrear;
    }

    public void cambiarIdioma(Locale locale) {

        ResourceBundle bundle = ResourceBundle.getBundle(
                "ec.edu.ups.proyectobiblioteca.i18n.mensajes",
                locale);

        setTitle(bundle.getString("tituloVentanaPrestamo"));

        panelCrearPrestamo.setBorder(
                javax.swing.BorderFactory.createTitledBorder(
                        bundle.getString("tituloPanelPrestamo")));

        lblCodigoCrear.setText(bundle.getString("lblCodigoPrestamo"));
        lblFechaCrear.setText(bundle.getString("lblFechaPrestamo"));
        lblFechaDevCrear.setText(bundle.getString("lblFechaDevPrestamo"));
        lblCedulaCrear.setText(bundle.getString("lblCedulaPrestamo"));
        lblUsuarioCrear.setText(bundle.getString("lblUsuarioPrestamo"));
        lblISBNCrear.setText(bundle.getString("lblISBNPrestamo"));
        lblLibroCrear.setText(bundle.getString("lblLibroPrestamo"));
        lblAutorCrear.setText(bundle.getString("lblAutorPrestamo"));
        lblDisponibleCrear.setText(bundle.getString("lblDisponiblePrestamo"));

        lblDateFormatp.setText(bundle.getString("lblFormatoFecha"));
        lblDateFormatd.setText(bundle.getString("lblFormatoFecha"));

        btnBuscarUsuario.setText(bundle.getString("botonBuscar"));
        btnBuscarLibro.setText(bundle.getString("botonBuscar"));

        btnAceptar.setText(bundle.getString("botonAceptar"));
        btnCancelar.setText(bundle.getString("botonCancelar"));
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearPrestamo = new javax.swing.JPanel();
        lblCodigoCrear = new javax.swing.JLabel();
        lblFechaCrear = new javax.swing.JLabel();
        lblISBNCrear = new javax.swing.JLabel();
        txtCodigoCrear = new javax.swing.JTextField();
        txtFechaCrear = new javax.swing.JTextField();
        txtISBNCrear = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblLibroCrear = new javax.swing.JLabel();
        lblAutorCrear = new javax.swing.JLabel();
        lblDisponibleCrear = new javax.swing.JLabel();
        txtDisponibleCrear = new javax.swing.JTextField();
        lblCedulaCrear = new javax.swing.JLabel();
        txtCedulaCrear = new javax.swing.JTextField();
        lblFechaDevCrear = new javax.swing.JLabel();
        txtFechaDevCrear = new javax.swing.JTextField();
        lblDateFormatp = new javax.swing.JLabel();
        lblDateFormatd = new javax.swing.JLabel();
        txtLibroCrear = new javax.swing.JTextField();
        txtAutorCrear = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        btnBuscarLibro = new javax.swing.JButton();
        lblUsuarioCrear = new javax.swing.JLabel();
        txtUsuarioCrear = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Prestamo\n");

        panelCrearPrestamo.setBackground(new java.awt.Color(255, 204, 51));
        panelCrearPrestamo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar datos del prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 12))); // NOI18N
        panelCrearPrestamo.setToolTipText("");

        lblCodigoCrear.setText("Código de préstamo:");

        lblFechaCrear.setText("Fecha de préstamo:");

        lblISBNCrear.setText("ISBN:");

        txtCodigoCrear.addActionListener(this::txtCodigoCrearActionPerformed);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblLibroCrear.setText("Libro:");

        lblAutorCrear.setText("Autor:");

        lblDisponibleCrear.setText("Disponible?");

        txtDisponibleCrear.setEditable(false);
        txtDisponibleCrear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        lblCedulaCrear.setText("Cédula:");

        txtCedulaCrear.addActionListener(this::txtCedulaCrearActionPerformed);

        lblFechaDevCrear.setText("Fecha de devolucion:");

        lblDateFormatp.setText("dd/mm/yyyy");

        lblDateFormatd.setText("dd/mm/yyyy");

        txtLibroCrear.setEditable(false);
        txtLibroCrear.addActionListener(this::txtLibroCrearActionPerformed);

        txtAutorCrear.setEditable(false);

        btnBuscarUsuario.setText("Buscar");

        btnBuscarLibro.setText("Buscar");

        lblUsuarioCrear.setText("Usuario:");

        txtUsuarioCrear.setEditable(false);

        javax.swing.GroupLayout panelCrearPrestamoLayout = new javax.swing.GroupLayout(panelCrearPrestamo);
        panelCrearPrestamo.setLayout(panelCrearPrestamoLayout);
        panelCrearPrestamoLayout.setHorizontalGroup(
            panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoCrear)
                            .addComponent(lblFechaDevCrear)
                            .addComponent(lblFechaCrear))
                        .addGap(39, 39, 39)
                        .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtCodigoCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtFechaDevCrear))
                        .addGap(37, 37, 37)
                        .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateFormatp)
                            .addComponent(lblDateFormatd)))
                    .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                        .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCedulaCrear)
                                    .addComponent(lblUsuarioCrear))
                                .addGap(50, 50, 50)
                                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCedulaCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtUsuarioCrear)))
                            .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                                        .addComponent(lblDisponibleCrear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(txtDisponibleCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                                        .addComponent(lblAutorCrear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAutorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                                        .addComponent(lblLibroCrear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                                        .addComponent(lblISBNCrear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtISBNCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(39, 39, 39)
                        .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarLibro)
                            .addComponent(btnBuscarUsuario)))
                    .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnAceptar)
                        .addGap(117, 117, 117)
                        .addComponent(btnCancelar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelCrearPrestamoLayout.setVerticalGroup(
            panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoCrear)
                    .addComponent(txtCodigoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateFormatp)
                    .addComponent(lblFechaCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaDevCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaDevCrear)
                    .addComponent(lblDateFormatd))
                .addGap(25, 25, 25)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaCrear)
                    .addComponent(txtCedulaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUsuario))
                .addGap(18, 18, 18)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioCrear)
                    .addComponent(txtUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBNCrear)
                    .addComponent(txtISBNCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarLibro))
                .addGap(18, 18, 18)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLibroCrear)
                    .addComponent(txtLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutorCrear)
                    .addComponent(txtAutorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisponibleCrear)
                    .addComponent(txtDisponibleCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCrearPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCrearPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCrearActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtLibroCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroCrearActionPerformed

    private void txtCedulaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblAutorCrear;
    private javax.swing.JLabel lblCedulaCrear;
    private javax.swing.JLabel lblCodigoCrear;
    private javax.swing.JLabel lblDateFormatd;
    private javax.swing.JLabel lblDateFormatp;
    private javax.swing.JLabel lblDisponibleCrear;
    private javax.swing.JLabel lblFechaCrear;
    private javax.swing.JLabel lblFechaDevCrear;
    private javax.swing.JLabel lblISBNCrear;
    private javax.swing.JLabel lblLibroCrear;
    private javax.swing.JLabel lblUsuarioCrear;
    private javax.swing.JPanel panelCrearPrestamo;
    private javax.swing.JTextField txtAutorCrear;
    private javax.swing.JTextField txtCedulaCrear;
    private javax.swing.JTextField txtCodigoCrear;
    private javax.swing.JTextField txtDisponibleCrear;
    private javax.swing.JTextField txtFechaCrear;
    private javax.swing.JTextField txtFechaDevCrear;
    private javax.swing.JTextField txtISBNCrear;
    private javax.swing.JTextField txtLibroCrear;
    private javax.swing.JTextField txtUsuarioCrear;
    // End of variables declaration//GEN-END:variables
}
