/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

import ec.edu.ups.proyectobiblioteca.models.Autor;
import ec.edu.ups.proyectobiblioteca.models.Libro;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateo
 */
public class ListarLibrosAutorView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;

    /**
     * Creates new form ListarLibrosAutorView
     */
    public ListarLibrosAutorView() {
        initComponents();
        configurarTabla();
    }

    public JComboBox<String> getAutorComboBoxListarLibros() {
        return AutorComboBoxListarLibros;
    }

    public void setAutorComboBoxListarLibros(JComboBox<String> AutorComboBoxListarLibros) {
        this.AutorComboBoxListarLibros = AutorComboBoxListarLibros;
    }

    public JButton getBtnListar() {
        return BtnListar;
    }

    public void setBtnListar(JButton BtnListar) {
        this.BtnListar = BtnListar;
    }

    public void configurarTabla() {

        modelo = new DefaultTableModel();

        modelo.addColumn("ISBN");
        modelo.addColumn("Título");
        modelo.addColumn("Editorial");
        modelo.addColumn("Categoría");
        modelo.addColumn("Disponible");

        jTable1.setModel(modelo);
    }

    public void cargarDatos(List<Libro> libros) {

        modelo.setRowCount(0);

        for (Libro libro : libros) {

            Object[] fila = {
                libro.getISBN(),
                libro.getTitulo(),
                libro.getEditorial(),
                libro.getCategoria(),
                libro.isDisponible()
            };

            modelo.addRow(fila);
        }
    }

    public void cargarAutores(List<Autor> autores) {

        AutorComboBoxListarLibros.removeAllItems();

        for (Autor autor : autores) {
            AutorComboBoxListarLibros.addItem(autor.getNombre());
        }
    }

    public void cambiarIdioma(Locale locale) {

        ResourceBundle bundle = ResourceBundle.getBundle(
                "ec.edu.ups.proyectobiblioteca.i18n.mensajes", locale);

        setTitle(bundle.getString("tituloVentanaListarLibrosAutor"));

        BtnListar.setText(bundle.getString("listarMenuItem"));

        modelo.setColumnIdentifiers(new Object[]{
            bundle.getString("colISBNLibro"),
            bundle.getString("colTituloLibro"),
            bundle.getString("colEditorialLibro"),
            bundle.getString("colCategoriaLibro"),
            bundle.getString("colDisponibleLibro")
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnListar = new javax.swing.JButton();
        AutorComboBoxListarLibros = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Lista Libros Del Autor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        BtnListar.setText("Listar");

        AutorComboBoxListarLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(AutorComboBoxListarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnListar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnListar)
                    .addComponent(AutorComboBoxListarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AutorComboBoxListarLibros;
    private javax.swing.JButton BtnListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
