/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.proyectobiblioteca.views;

/**
 *
 * @author Asus
 */
public class PrincipalView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalView.class.getName());

    /**
     * Creates new form PrincipalVoew
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        PrestamoMenu = new javax.swing.JMenu();
        CrearPrestamoMenuItem = new javax.swing.JMenuItem();
        BuscarPrestamoMenuItem = new javax.swing.JMenuItem();
        EliminarPrestamoMenuItem = new javax.swing.JMenuItem();
        ActualizarPrestamoMenuItem = new javax.swing.JMenuItem();
        ListarPrestamoMenuItem = new javax.swing.JMenuItem();
        LibroMenu = new javax.swing.JMenu();
        AgregarLibroMenuItem = new javax.swing.JMenuItem();
        EliminarLibroMenuItem = new javax.swing.JMenuItem();
        ActualizarLibroMenuItem = new javax.swing.JMenuItem();
        BuscarLibroMenuItem = new javax.swing.JMenuItem();
        ListarLibroMenuItem = new javax.swing.JMenuItem();
        AutorMenu = new javax.swing.JMenu();
        AgregarAutorMenuItem = new javax.swing.JMenuItem();
        EliminarAutorMenuItem = new javax.swing.JMenuItem();
        ActualizarAutorMenuItem = new javax.swing.JMenuItem();
        ListarLibroAutorMenuItem = new javax.swing.JMenuItem();
        UsuariosMenu = new javax.swing.JMenu();
        AgregarUsuarioMenuItem = new javax.swing.JMenuItem();
        EliminarUsuarioMenuItem = new javax.swing.JMenuItem();
        ActualizarUsuarioMenuItem = new javax.swing.JMenuItem();
        BuscarUsuarioMenuItem = new javax.swing.JMenuItem();
        ListarUsuarioMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        PrestamoMenu.setText("Prestamo");

        CrearPrestamoMenuItem.setText("Crear");
        PrestamoMenu.add(CrearPrestamoMenuItem);

        BuscarPrestamoMenuItem.setText("Buscar");
        PrestamoMenu.add(BuscarPrestamoMenuItem);

        EliminarPrestamoMenuItem.setText("Eliminar");
        PrestamoMenu.add(EliminarPrestamoMenuItem);

        ActualizarPrestamoMenuItem.setText("Actualizar");
        PrestamoMenu.add(ActualizarPrestamoMenuItem);

        ListarPrestamoMenuItem.setText("Listar");
        ListarPrestamoMenuItem.addActionListener(this::ListarPrestamoMenuItemActionPerformed);
        PrestamoMenu.add(ListarPrestamoMenuItem);

        jMenuBar2.add(PrestamoMenu);

        LibroMenu.setText("Libro");

        AgregarLibroMenuItem.setText("Agregar");
        AgregarLibroMenuItem.addActionListener(this::AgregarLibroMenuItemActionPerformed);
        LibroMenu.add(AgregarLibroMenuItem);

        EliminarLibroMenuItem.setText("Eliminar");
        LibroMenu.add(EliminarLibroMenuItem);

        ActualizarLibroMenuItem.setText("Actualizar");
        ActualizarLibroMenuItem.addActionListener(this::ActualizarLibroMenuItemActionPerformed);
        LibroMenu.add(ActualizarLibroMenuItem);

        BuscarLibroMenuItem.setText("Buscar");
        LibroMenu.add(BuscarLibroMenuItem);

        ListarLibroMenuItem.setText("Listar");
        ListarLibroMenuItem.addActionListener(this::ListarLibroMenuItemActionPerformed);
        LibroMenu.add(ListarLibroMenuItem);

        jMenuBar2.add(LibroMenu);

        AutorMenu.setText("Autor");

        AgregarAutorMenuItem.setText("Agregar");
        AutorMenu.add(AgregarAutorMenuItem);

        EliminarAutorMenuItem.setText("Eliminar");
        EliminarAutorMenuItem.addActionListener(this::EliminarAutorMenuItemActionPerformed);
        AutorMenu.add(EliminarAutorMenuItem);

        ActualizarAutorMenuItem.setText("Actualizar");
        AutorMenu.add(ActualizarAutorMenuItem);

        ListarLibroAutorMenuItem.setText("Listar Libros");
        ListarLibroAutorMenuItem.addActionListener(this::ListarLibroAutorMenuItemActionPerformed);
        AutorMenu.add(ListarLibroAutorMenuItem);

        jMenuBar2.add(AutorMenu);

        UsuariosMenu.setText("Usuarios");

        AgregarUsuarioMenuItem.setText("Agregar");
        UsuariosMenu.add(AgregarUsuarioMenuItem);

        EliminarUsuarioMenuItem.setText("Eliminar");
        EliminarUsuarioMenuItem.addActionListener(this::EliminarUsuarioMenuItemActionPerformed);
        UsuariosMenu.add(EliminarUsuarioMenuItem);

        ActualizarUsuarioMenuItem.setText("Actualizar");
        UsuariosMenu.add(ActualizarUsuarioMenuItem);

        BuscarUsuarioMenuItem.setText("Buscar");
        BuscarUsuarioMenuItem.addActionListener(this::BuscarUsuarioMenuItemActionPerformed);
        UsuariosMenu.add(BuscarUsuarioMenuItem);

        ListarUsuarioMenuItem.setText("Listar");
        UsuariosMenu.add(ListarUsuarioMenuItem);

        jMenuBar2.add(UsuariosMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarLibroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLibroMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarLibroMenuItemActionPerformed

    private void ActualizarLibroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarLibroMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarLibroMenuItemActionPerformed

    private void ListarLibroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarLibroMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarLibroMenuItemActionPerformed

    private void EliminarAutorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAutorMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarAutorMenuItemActionPerformed

    private void EliminarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarUsuarioMenuItemActionPerformed

    private void BuscarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarUsuarioMenuItemActionPerformed

    private void ListarPrestamoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPrestamoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarPrestamoMenuItemActionPerformed

    private void ListarLibroAutorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarLibroAutorMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarLibroAutorMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarAutorMenuItem;
    private javax.swing.JMenuItem ActualizarLibroMenuItem;
    private javax.swing.JMenuItem ActualizarPrestamoMenuItem;
    private javax.swing.JMenuItem ActualizarUsuarioMenuItem;
    private javax.swing.JMenuItem AgregarAutorMenuItem;
    private javax.swing.JMenuItem AgregarLibroMenuItem;
    private javax.swing.JMenuItem AgregarUsuarioMenuItem;
    private javax.swing.JMenu AutorMenu;
    private javax.swing.JMenuItem BuscarLibroMenuItem;
    private javax.swing.JMenuItem BuscarPrestamoMenuItem;
    private javax.swing.JMenuItem BuscarUsuarioMenuItem;
    private javax.swing.JMenuItem CrearPrestamoMenuItem;
    private javax.swing.JMenuItem EliminarAutorMenuItem;
    private javax.swing.JMenuItem EliminarLibroMenuItem;
    private javax.swing.JMenuItem EliminarPrestamoMenuItem;
    private javax.swing.JMenuItem EliminarUsuarioMenuItem;
    private javax.swing.JMenu LibroMenu;
    private javax.swing.JMenuItem ListarLibroAutorMenuItem;
    private javax.swing.JMenuItem ListarLibroMenuItem;
    private javax.swing.JMenuItem ListarPrestamoMenuItem;
    private javax.swing.JMenuItem ListarUsuarioMenuItem;
    private javax.swing.JMenu PrestamoMenu;
    private javax.swing.JMenu UsuariosMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
